package masecla.prompt.classes;

import java.io.File;

public class CreateMIMEType {
	private File tfile;

	public CreateMIMEType(File file) {
		tfile = file;
	}


	public String getMIMEText() {
		String ext = tfile.getName().split("\\.")[1];
		if (ext.equalsIgnoreCase("evy"))
			return "application/envoy";
		if (ext.equalsIgnoreCase("fif"))
			return "application/fractals";
		if (ext.equalsIgnoreCase("spl"))
			return "application/futuresplash";
		if (ext.equalsIgnoreCase("hta"))
			return "application/hta";
		if (ext.equalsIgnoreCase("acx"))
			return "application/internet-property-stream";
		if (ext.equalsIgnoreCase("hqx"))
			return "application/mac-binhex40";
		if (ext.equalsIgnoreCase("doc") || ext.equalsIgnoreCase("dot"))
			return "application/msword";
		if (ext.equalsIgnoreCase("oda"))
			return "application/oda";
		if (ext.equalsIgnoreCase("axs"))
			return "application/olescript";
		if (ext.equalsIgnoreCase("pdf"))
			return "application/pdf";
		if (ext.equalsIgnoreCase("prf"))
			return "application/pics-rules";
		if (ext.equalsIgnoreCase("p10"))
			return "application/pkcs10";
		if (ext.equalsIgnoreCase("crl"))
			return "application/pkix-crl";
		if (ext.equalsIgnoreCase("ai"))
			return "application/postscript";
		if (ext.equalsIgnoreCase("eps"))
			return "application/postscript";
		if (ext.equalsIgnoreCase("ps"))
			return "application/postscript";
		if (ext.equalsIgnoreCase("rtf"))
			return "application/rtf";
		if (ext.equalsIgnoreCase("setpay"))
			return "application/set-payment-initiation";
		if (ext.equalsIgnoreCase("setreg"))
			return "application/set-registration-initiation";
		if (ext.equalsIgnoreCase("xla") || ext.equalsIgnoreCase("xlc") || ext.equalsIgnoreCase("xlm")
				|| ext.equalsIgnoreCase("xls") || ext.equalsIgnoreCase("xlt") || ext.equalsIgnoreCase("xlw"))
			return "application/vnd.ms-excel";
		if (ext.equalsIgnoreCase("msg"))
			return "application/vnd.ms-outlook";
		if (ext.equalsIgnoreCase("sst"))
			return "application/vnd.ms-pkicertstore";
		if (ext.equalsIgnoreCase("cat"))
			return "application/vnd.ms-pkiseccat";
		if (ext.equalsIgnoreCase("stl"))
			return "application/vnd.ms-pkistl";
		if (ext.equalsIgnoreCase("pot") || ext.equalsIgnoreCase("pps") || ext.equalsIgnoreCase("ppt"))
			return "application/vnd.ms-powerpoint";
		if (ext.equalsIgnoreCase("mpp"))
			return "application/vnd.ms-project";
		if (ext.equalsIgnoreCase("wps") || ext.equalsIgnoreCase("wks") || ext.equalsIgnoreCase("wcm")
				|| ext.equalsIgnoreCase("wdb"))
			return "application/vnd.ms-works";
		if (ext.equalsIgnoreCase("hlp"))
			return "application/winhlp";
		if (ext.equalsIgnoreCase("bcpio"))
			return "application/x-bcpio";
		if (ext.equalsIgnoreCase("cdf"))
			return "application/x-cdf";
		if (ext.equalsIgnoreCase("z"))
			return "application/x-compress";
		if (ext.equalsIgnoreCase("tgz"))
			return "application/x-compressed";
		if (ext.equalsIgnoreCase("cpio"))
			return "application/x-cpio";
		if (ext.equalsIgnoreCase("csh"))
			return "application/x-csh";
		if (ext.equalsIgnoreCase("dcr"))
			return "application/x-director";
		if (ext.equalsIgnoreCase("dir"))
			return "application/x-director";
		if (ext.equalsIgnoreCase("dxr"))
			return "application/x-director";
		if (ext.equalsIgnoreCase("dvi"))
			return "application/x-dvi";
		if (ext.equalsIgnoreCase("gtar"))
			return "application/x-gtar";
		if (ext.equalsIgnoreCase("gz"))
			return "application/x-gzip";
		if (ext.equalsIgnoreCase("hdf"))
			return "application/x-hdf";
		if (ext.equalsIgnoreCase("ins"))
			return "application/x-internet-signup";
		if (ext.equalsIgnoreCase("isp"))
			return "application/x-internet-signup";
		if (ext.equalsIgnoreCase("iii"))
			return "application/x-iphone";
		if (ext.equalsIgnoreCase("js"))
			return "application/x-javascript";
		if (ext.equalsIgnoreCase("latex"))
			return "application/x-latex";
		if (ext.equalsIgnoreCase("mdb"))
			return "application/x-msaccess";
		if (ext.equalsIgnoreCase("crd"))
			return "application/x-mscardfile";
		if (ext.equalsIgnoreCase("clp"))
			return "application/x-msclip";
		if (ext.equalsIgnoreCase("dll"))
			return "application/x-msdownload";
		if (ext.equalsIgnoreCase("m13"))
			return "application/x-msmediaview";
		if (ext.equalsIgnoreCase("m14"))
			return "application/x-msmediaview";
		if (ext.equalsIgnoreCase("mvb"))
			return "application/x-msmediaview";
		if (ext.equalsIgnoreCase("wmf"))
			return "application/x-msmetafile";
		if (ext.equalsIgnoreCase("mny"))
			return "application/x-msmoney";
		if (ext.equalsIgnoreCase("pub"))
			return "application/x-mspublisher";
		if (ext.equalsIgnoreCase("scd"))
			return "application/x-msschedule";
		if (ext.equalsIgnoreCase("trm"))
			return "application/x-msterminal";
		if (ext.equalsIgnoreCase("wri"))
			return "application/x-mswrite";
		if (ext.equalsIgnoreCase("cdf"))
			return "application/x-netcdf";
		if (ext.equalsIgnoreCase("nc"))
			return "application/x-netcdf";
		if (ext.equalsIgnoreCase("pma"))
			return "application/x-perfmon";
		if (ext.equalsIgnoreCase("pmc"))
			return "application/x-perfmon";
		if (ext.equalsIgnoreCase("pml"))
			return "application/x-perfmon";
		if (ext.equalsIgnoreCase("pmr"))
			return "application/x-perfmon";
		if (ext.equalsIgnoreCase("pmw"))
			return "application/x-perfmon";
		if (ext.equalsIgnoreCase("p12"))
			return "application/x-pkcs12";
		if (ext.equalsIgnoreCase("pfx"))
			return "application/x-pkcs12";
		if (ext.equalsIgnoreCase("p7b"))
			return "application/x-pkcs7-certificates";
		if (ext.equalsIgnoreCase("spc"))
			return "application/x-pkcs7-certificates";
		if (ext.equalsIgnoreCase("p7r"))
			return "application/x-pkcs7-certreqresp";
		if (ext.equalsIgnoreCase("p7c"))
			return "application/x-pkcs7-mime";
		if (ext.equalsIgnoreCase("p7m"))
			return "application/x-pkcs7-mime";
		if (ext.equalsIgnoreCase("p7s"))
			return "application/x-pkcs7-signature";
		if (ext.equalsIgnoreCase("sh"))
			return "application/x-sh";
		if (ext.equalsIgnoreCase("shar"))
			return "application/x-shar";
		if (ext.equalsIgnoreCase("swf"))
			return "application/x-shockwave-flash";
		if (ext.equalsIgnoreCase("sit"))
			return "application/x-stuffit";
		if (ext.equalsIgnoreCase("sv4cpio"))
			return "application/x-sv4cpio";
		if (ext.equalsIgnoreCase("sv4crc"))
			return "application/x-sv4crc";
		if (ext.equalsIgnoreCase("tar"))
			return "application/x-tar";
		if (ext.equalsIgnoreCase("tcl"))
			return "application/x-tcl";
		if (ext.equalsIgnoreCase("tex"))
			return "application/x-tex";
		if (ext.equalsIgnoreCase("texi"))
			return "application/x-texinfo";
		if (ext.equalsIgnoreCase("texinfo"))
			return "application/x-texinfo";
		if (ext.equalsIgnoreCase("roff"))
			return "application/x-troff";
		if (ext.equalsIgnoreCase("t"))
			return "application/x-troff";
		if (ext.equalsIgnoreCase("tr"))
			return "application/x-troff";
		if (ext.equalsIgnoreCase("man"))
			return "application/x-troff-man";
		if (ext.equalsIgnoreCase("me"))
			return "application/x-troff-me";
		if (ext.equalsIgnoreCase("ms"))
			return "application/x-troff-ms";
		if (ext.equalsIgnoreCase("ustar"))
			return "application/x-ustar";
		if (ext.equalsIgnoreCase("src"))
			return "application/x-wais-source";
		if (ext.equalsIgnoreCase("cer"))
			return "application/x-x509-ca-cert";
		if (ext.equalsIgnoreCase("crt"))
			return "application/x-x509-ca-cert";
		if (ext.equalsIgnoreCase("der"))
			return "application/x-x509-ca-cert";
		if (ext.equalsIgnoreCase("pko"))
			return "application/ynd.ms-pkipko";
		if (ext.equalsIgnoreCase("zip"))
			return "application/zip";
		if (ext.equalsIgnoreCase("au"))
			return "audio/basic";
		if (ext.equalsIgnoreCase("snd"))
			return "audio/basic";
		if (ext.equalsIgnoreCase("mid"))
			return "audio/mid";
		if (ext.equalsIgnoreCase("rmi"))
			return "audio/mid";
		if (ext.equalsIgnoreCase("mp3"))
			return "audio/mpeg";
		if (ext.equalsIgnoreCase("aif"))
			return "audio/x-aiff";
		if (ext.equalsIgnoreCase("aifc"))
			return "audio/x-aiff";
		if (ext.equalsIgnoreCase("aiff"))
			return "audio/x-aiff";
		if (ext.equalsIgnoreCase("m3u"))
			return "audio/x-mpegurl";
		if (ext.equalsIgnoreCase("ra"))
			return "audio/x-pn-realaudio";
		if (ext.equalsIgnoreCase("ram"))
			return "audio/x-pn-realaudio";
		if (ext.equalsIgnoreCase("wav"))
			return "audio/x-wav";
		if (ext.equalsIgnoreCase("bmp"))
			return "image/bmp";
		if (ext.equalsIgnoreCase("cod"))
			return "image/cis-cod";
		if (ext.equalsIgnoreCase("gif"))
			return "image/gif";
		if (ext.equalsIgnoreCase("ief"))
			return "image/ief";
		if (ext.equalsIgnoreCase("png"))
			return "image/png";
		if (ext.equalsIgnoreCase("jpe"))
			return "image/jpeg";
		if (ext.equalsIgnoreCase("jpeg"))
			return "image/jpeg";
		if (ext.equalsIgnoreCase("jpg"))
			return "image/jpeg";
		if (ext.equalsIgnoreCase("jfif"))
			return "image/pipeg";
		if (ext.equalsIgnoreCase("svg"))
			return "image/svg+xml";
		if (ext.equalsIgnoreCase("tif"))
			return "image/tiff";
		if (ext.equalsIgnoreCase("tiff"))
			return "image/tiff";
		if (ext.equalsIgnoreCase("ras"))
			return "image/x-cmu-raster";
		if (ext.equalsIgnoreCase("ico"))
			return "image/x-icon";
		if (ext.equalsIgnoreCase("pnm"))
			return "image/x-portable-anymap";
		if (ext.equalsIgnoreCase("pbm"))
			return "image/x-portable-bitmap";
		if (ext.equalsIgnoreCase("pgm"))
			return "image/x-portable-graymap";
		if (ext.equalsIgnoreCase("ppm"))
			return "image/x-portable-pixmap";
		if (ext.equalsIgnoreCase("rgb"))
			return "image/x-rgb";
		if (ext.equalsIgnoreCase("xbm"))
			return "image/x-xbitmap";
		if (ext.equalsIgnoreCase("xpm"))
			return "image/x-xpixmap";
		if (ext.equalsIgnoreCase("xwd"))
			return "image/x-xwindowdump";
		if (ext.equalsIgnoreCase("mht"))
			return "message/rfc822";
		if (ext.equalsIgnoreCase("mhtml"))
			return "message/rfc822";
		if (ext.equalsIgnoreCase("nws"))
			return "message/rfc822";
		if (ext.equalsIgnoreCase("css"))
			return "text/css";
		if (ext.equalsIgnoreCase("323"))
			return "text/h323";
		if (ext.equalsIgnoreCase("htm"))
			return "text/html";
		if (ext.equalsIgnoreCase("html"))
			return "text/html";
		if (ext.equalsIgnoreCase("stm"))
			return "text/html";
		if (ext.equalsIgnoreCase("uls"))
			return "text/iuls";
		if (ext.equalsIgnoreCase("bas"))
			return "text/plain";
		if (ext.equalsIgnoreCase("c"))
			return "text/plain";
		if (ext.equalsIgnoreCase("h"))
			return "text/plain";
		if (ext.equalsIgnoreCase("txt"))
			return "text/plain";
		if (ext.equalsIgnoreCase("rtx"))
			return "text/richtext";
		if (ext.equalsIgnoreCase("sct"))
			return "text/scriptlet";
		if (ext.equalsIgnoreCase("tsv"))
			return "text/tab-separated-values";
		if (ext.equalsIgnoreCase("htt"))
			return "text/webviewhtml";
		if (ext.equalsIgnoreCase("htc"))
			return "text/x-component";
		if (ext.equalsIgnoreCase("etx"))
			return "text/x-setext";
		if (ext.equalsIgnoreCase("vcf"))
			return "text/x-vcard";
		if (ext.equalsIgnoreCase("mp2"))
			return "video/mpeg";
		if (ext.equalsIgnoreCase("mpa"))
			return "video/mpeg";
		if (ext.equalsIgnoreCase("mpe"))
			return "video/mpeg";
		if (ext.equalsIgnoreCase("mpeg"))
			return "video/mpeg";
		if (ext.equalsIgnoreCase("mpg"))
			return "video/mpeg";
		if (ext.equalsIgnoreCase("mpv2"))
			return "video/mpeg";
		if (ext.equalsIgnoreCase("mp4"))
			return "video/mp4";
		if (ext.equalsIgnoreCase("mov"))
			return "video/quicktime";
		if (ext.equalsIgnoreCase("qt"))
			return "video/quicktime";
		if (ext.equalsIgnoreCase("lsf"))
			return "video/x-la-asf";
		if (ext.equalsIgnoreCase("lsx"))
			return "video/x-la-asf";
		if (ext.equalsIgnoreCase("asf"))
			return "video/x-ms-asf";
		if (ext.equalsIgnoreCase("asr"))
			return "video/x-ms-asf";
		if (ext.equalsIgnoreCase("asx"))
			return "video/x-ms-asf";
		if (ext.equalsIgnoreCase("avi"))
			return "video/x-msvideo";
		if (ext.equalsIgnoreCase("movie"))
			return "video/x-sgi-movie";
		if (ext.equalsIgnoreCase("flr"))
			return "x-world/x-vrml";
		if (ext.equalsIgnoreCase("vrml"))
			return "x-world/x-vrml";
		if (ext.equalsIgnoreCase("wrl"))
			return "x-world/x-vrml";
		if (ext.equalsIgnoreCase("wrz"))
			return "x-world/x-vrml";
		if (ext.equalsIgnoreCase("xaf"))
			return "x-world/x-vrml";
		if (ext.equalsIgnoreCase("xof"))
			return "x-world/x-vrml";
		return "application/octet-stream";
	}
}
